# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from joystick/JoyStick.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JoyStick(genpy.Message):
  _md5sum = "529be6a2e8574e4ce2287a2d5c8ed377"
  _type = "joystick/JoyStick"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 steering
float32 throttle
bool brk_status
bool rec_status"""
  __slots__ = ['steering','throttle','brk_status','rec_status']
  _slot_types = ['float32','float32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       steering,throttle,brk_status,rec_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JoyStick, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.steering is None:
        self.steering = 0.
      if self.throttle is None:
        self.throttle = 0.
      if self.brk_status is None:
        self.brk_status = False
      if self.rec_status is None:
        self.rec_status = False
    else:
      self.steering = 0.
      self.throttle = 0.
      self.brk_status = False
      self.rec_status = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f2B().pack(_x.steering, _x.throttle, _x.brk_status, _x.rec_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.steering, _x.throttle, _x.brk_status, _x.rec_status,) = _get_struct_2f2B().unpack(str[start:end])
      self.brk_status = bool(self.brk_status)
      self.rec_status = bool(self.rec_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f2B().pack(_x.steering, _x.throttle, _x.brk_status, _x.rec_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.steering, _x.throttle, _x.brk_status, _x.rec_status,) = _get_struct_2f2B().unpack(str[start:end])
      self.brk_status = bool(self.brk_status)
      self.rec_status = bool(self.rec_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f2B = None
def _get_struct_2f2B():
    global _struct_2f2B
    if _struct_2f2B is None:
        _struct_2f2B = struct.Struct("<2f2B")
    return _struct_2f2B
